author = "hill"
base_url = "https://hilll.dev"
build_search_index = true
compile_sass = true
feed_filenames = ["atom.xml", "rss.xml"]
generate_feeds = true
hard_link_static = true
minify_html = true


[markdown]
highlight_code = true
highlight_thme = "solarized-light"
render_emoji = false
external_links_target_blank = false
external_links_no_follow = false
external_links_no_referrer = true
smart_punctuation = false


[link_checker]
internal_level = "error"
external_level = "error"


[slugify]
paths = "on"
taxonomies = "on"
anchors = "on"
paths_keep_dates = false


[search]
include_title = true
include_description = true
include_path = true
include_content = true
index_format = "elasticlunr_javascript"

[extra]
